services:
  web:
    build: ./web
    command: gunicorn -c ./conf/gunicorn/dev.py
    volumes:
      - ./web:/usr/src/app/
      - static:/usr/src/app/static
      - Media:/usr/src/app/Media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    command: ["sh", "-c", "cp -r /front/static/* /static/ && nginx -g 'daemon off;'"]
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static:/static
      - Media:/Media
      - ./front/build:/front

volumes:
  Media:
  static:
  postgres_data: