# Generated by Django 4.2 on 2024-10-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=555)),
                ('status', models.CharField(choices=[('A', 'در انتظار بررسی'), ('D', 'تعیین وضعیت شده'), ('E', 'منقضی شده'), ('P', 'پرداخت شده')], default='A', max_length=1)),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('field', models.CharField(max_length=255, verbose_name='رشته تحصیلی')),
                ('degree', models.CharField(choices=[('D', 'دیپلم'), ('A', 'کاردانی'), ('B', 'کارشناسی'), ('M', 'ارشد'), ('P', 'دکترا')], max_length=1, verbose_name='مقطع تحصیلی')),
                ('title', models.CharField(max_length=555, verbose_name='عنوان')),
                ('caption', models.CharField(blank=True, max_length=2000, null=True, verbose_name='توضیحات تکمیلی')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'سفارشات',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
