# Generated by Django 4.2 on 2024-10-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='order',
            name='field',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('A', 'در انتظار بررسی'), ('B', 'در انتظار پرداخت'), ('C', 'پرداخت شده، در حال پردازش'), ('D', 'تحویل داده شده')], default='A', max_length=1),
        ),
    ]
