# Generated by Django 4.2 on 2024-10-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_remove_order_degree_remove_order_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'فعال'), ('Paid', 'پرداخت شده'), ('Expired', 'منقضی شده'), ('Failed', 'پرداخت ناموفق')], max_length=20)),
                ('authority', models.CharField(blank=True, max_length=36)),
                ('url', models.CharField(max_length=555)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'verbose_name': 'پرداخت ها',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
