# Generated by Django 4.2 on 2024-10-27 08:25

import blog.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/BlogCategory/')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True)),
                ('caption', models.CharField(max_length=555, verbose_name='توضیحات کوتاه')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='منتشر شده در')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, validators=[blog.models.validate_tags], verbose_name="تگ (با '_' جدا می شوند)")),
                ('is_promoted', models.BooleanField(default=False, verbose_name='انتشار در صفحه اصلی')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='توضیحات')),
                ('banner', models.ImageField(upload_to='blog/postBanner/', verbose_name='بنر پست')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پُست',
                'verbose_name_plural': 'پُست ها',
            },
        ),
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=555)),
                ('written_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='SavedPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'verbose_name': 'پست ذخیره شده',
                'verbose_name_plural': 'پست های ذخیره شده',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
