# Generated by Django 4.2 on 2024-10-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره تلفن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='accounts/UserProfile/', verbose_name='تصویر پروفایل')),
                ('field', models.CharField(blank=True, null=True, verbose_name='رشته تحصیلی')),
                ('degree', models.CharField(blank=True, choices=[('D', 'دیپلم'), ('A', 'کاردانی'), ('B', 'کارشناسی'), ('M', 'ارشد'), ('P', 'دکترا')], max_length=1, null=True, verbose_name='مقطع تحصیلی')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربران',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
